### PR TITLE
💄 Success page

### PR DESCRIPTION
**Pull request by vikingviolinist**
- 🔧 Check against db stock instead local
- ♻️  Refactor success page

### CODE REVIEW

**Review by csandven — APPROVED** [review]
Nice! But it kind of leads me to think that we should cache things the traditional way (backend) rather then the localstorage. What do you think? I have a feeling that it could be simpler to handle data from only one source.

**Comment by vikingviolinist** [comment]
> Nice! But it kind of leads me to think that we should cache things the traditional way (backend) rather then the localstorage. What do you think? I have a feeling that it could be simpler to handle data from only one source.
> 
> 

Not sure what you mean by that? There is no caching🤔 The only think we cache is the theme preference.

**Comment by csandven** [comment]
> > Nice! But it kind of leads me to think that we should cache things the traditional way (backend) rather then the localstorage. What do you think? I have a feeling that it could be simpler to handle data from only one source.
> 
> Not sure what you mean by that? There is no caching🤔 The only think we cache is the theme preference.

Oh. Maybe we already removed that earlier.

**Comment by vikingviolinist** [comment]
> > > Nice! But it kind of leads me to think that we should cache things the traditional way (backend) rather then the localstorage. What do you think? I have a feeling that it could be simpler to handle data from only one source.
> 
> > 
> 
> > Not sure what you mean by that? There is no caching🤔 The only think we cache is the theme preference.
> 
> 
> 
> Oh. Maybe we already removed that earlier. 

Yeah, products used to be stored in localStorage before, but that's not the case anymore😊

**Pull request merged**
